--
-- Maven Auto Database to Liquibase Generator Plugin
-- 2.1.3
--
-- Name: combined_transactions

create view combined_transactions as  SELECT exploded_transactions.id,
    exploded_transactions.subtype,
    exploded_transactions.status,
    exploded_transactions.executed_at,
    exploded_transactions.address_geo,
    exploded_transactions.address_ip,
    exploded_transactions.address_country_code,
    exploded_transactions.s_context,
    exploded_transactions.s_entity_id,
    exploded_transactions.s_instrument_id,
    exploded_transactions.s_amount,
    exploded_transactions.s_currency,
    exploded_transactions.r_context,
    exploded_transactions.r_entity_id,
    exploded_transactions.r_instrument_id,
    exploded_transactions.r_amount,
    exploded_transactions.r_currency,
    exploded_transactions.c_trx_channel,
    exploded_transactions.c_trx_product,
    exploded_transactions.c_trx_code,
    exploded_transactions.c_trx_branch_code,
    exploded_transactions.c_trx_name,
    exploded_transactions.c_trx_bank_name,
    exploded_transactions.c_trx_bank_code,
    exploded_transactions.c_trx_message,
    exploded_transactions.c_trx_commerce_code,
    exploded_transactions.c_trx_commerce_name,
    exploded_transactions.c_cli_fan_acc
   FROM exploded_transactions
UNION
 SELECT exploded_transactions_historic.id,
    exploded_transactions_historic.subtype,
    exploded_transactions_historic.status,
    exploded_transactions_historic.executed_at,
    exploded_transactions_historic.address_geo,
    exploded_transactions_historic.address_ip,
    exploded_transactions_historic.address_country_code,
    exploded_transactions_historic.s_context,
    exploded_transactions_historic.s_entity_id,
    exploded_transactions_historic.s_instrument_id,
    exploded_transactions_historic.s_amount,
    exploded_transactions_historic.s_currency,
    exploded_transactions_historic.r_context,
    exploded_transactions_historic.r_entity_id,
    exploded_transactions_historic.r_instrument_id,
    exploded_transactions_historic.r_amount,
    exploded_transactions_historic.r_currency,
    exploded_transactions_historic.c_trx_channel,
    exploded_transactions_historic.c_trx_product,
    exploded_transactions_historic.c_trx_code,
    exploded_transactions_historic.c_trx_branch_code,
    exploded_transactions_historic.c_trx_name,
    exploded_transactions_historic.c_trx_bank_name,
    exploded_transactions_historic.c_trx_bank_code,
    exploded_transactions_historic.c_trx_message,
    exploded_transactions_historic.c_trx_commerce_code,
    exploded_transactions_historic.c_trx_commerce_name,
    exploded_transactions_historic.c_cli_fan_acc
   FROM exploded_transactions_historic;
