--
-- Maven Auto Database to Liquibase Generator Plugin
-- 2.1.3
--
-- Name: exploded_transactions_search

create view exploded_transactions_search as  SELECT et.id,
    et.subtype,
    et.status,
    et.executed_at,
    et.address_geo,
    et.address_ip,
    et.address_country_code,
    et.s_context,
    et.s_entity_id,
    et.s_amount,
    et.s_currency,
    et.r_context,
    et.r_amount,
    et.r_currency,
    et.c_trx_channel,
    et.c_trx_product,
    et.c_trx_code,
    et.c_trx_branch_code,
    et.c_trx_name,
    et.c_trx_bank_name,
    et.c_trx_bank_code,
    et.c_trx_message,
    et.c_trx_commerce_code,
    et.c_trx_commerce_name,
    et.c_cli_fan_acc,
    re.id AS r_e_id,
    re.registered_at AS r_e_registered_at,
    re.type AS r_e_type,
    re.subtype AS r_e_subtype,
    re.status AS r_e_status,
    re.name AS r_e_name,
    re.year_of_birth AS r_e_year_of_birth,
    re.month_of_birth AS r_e_month_of_birth,
    re.day_of_birth AS r_e_day_of_birth,
    re.gender AS r_e_gender,
    re.custom_data AS r_e_custom_data,
    re.national_identification_number AS r_e_nin,
    ri.id AS r_i_id,
    ri.registered_at AS r_i_registered_at,
    ri.type AS r_i_type,
    ri.subtype AS r_i_subtype,
    ri.status AS r_i_status,
    ri.source AS r_i_source,
    ri.custom_data AS r_i_custom_data,
    se.id AS s_e_id,
    se.registered_at AS s_e_registered_at,
    se.type AS s_e_type,
    se.subtype AS s_e_subtype,
    se.status AS s_e_status,
    se.name AS s_e_name,
    se.year_of_birth AS s_e_year_of_birth,
    se.month_of_birth AS s_e_month_of_birth,
    se.day_of_birth AS s_e_day_of_birth,
    se.gender AS s_e_gender,
    se.custom_data AS s_e_custom_data,
    se.national_identification_number AS s_e_nin,
    si.id AS s_i_id,
    si.registered_at AS s_i_registered_at,
    si.type AS s_i_type,
    si.subtype AS s_i_subtype,
    si.status AS s_i_status,
    si.source AS s_i_source,
    si.custom_data AS s_i_custom_data,
    se.pep AS s_e_pep,
    se.risk_score AS s_e_risk_score,
    re.pep AS r_e_pep,
    re.risk_score AS r_e_risk_score
   FROM ((((exploded_transactions_historic et
     LEFT JOIN entities re ON (((et.r_entity_id)::text = (re.id)::text)))
     LEFT JOIN instruments ri ON (((et.r_instrument_id)::text = (ri.id)::text)))
     LEFT JOIN entities se ON (((et.s_entity_id)::text = (se.id)::text)))
     LEFT JOIN instruments si ON (((et.s_instrument_id)::text = (si.id)::text)));
